### ISSUE TITLE
doesn't watch breakpoints for changes

### ISSUE THREAD

**Issue by contra** [jxnblk/reflexbox#10]
resizing has no effect because the breakpoints are only detected on render.

maybe use something like https://github.com/contra/react-responsive under the hood?

( or take the code from it that handles watching for changes )

**Comment by jxnblk** [comment]
I built this intending not to implement any window listeners, and instead opt to allow users to handle that within their application. I've thought about adding a breakpoint/viewport-width variable to the context, to allow the grid to re-render without having to force it, but generally I'd like to keep the implementation of listening to window events outside the scope of these components.

**Comment by jxnblk** [comment]
Related: #6

**Comment by contra** [comment]
Hmm, I'm trying to think if there's any way you can enable users to do this on their own without adding a lot of new API surface. What about passing current media state in as a context attribute. Right now there's no way to pass this stuff in so you can't do it without writing a new library.
