### ISSUE TITLE
Investigate better fallback solutions for server-rendering

### ISSUE THREAD

**Issue by jxnblk** [jxnblk/reflexbox#13]

**Comment by jxnblk** [comment]
Related: #6

**Comment by frankleng** [comment]
@jxnblk any update on this?

**Comment by steida** [comment]
I think, it must be a CSS only solution.

**Comment by steida** [comment]
I think it should be fine as is because it will be updated after initial render. I tested it with the server side rendering in https://github.com/este/este and it works. Can be closed imho.

**Comment by steida** [comment]
There is a general pattern in the server side rendering, that initial render must be the same because there are a lot of client specific stuff like settings stored in localStorage, current language etc. So the current reflexbox is fine.

**Comment by jxnblk** [comment]
Thanks, it certainly works as-is for server-side rendering. This issue was meant as a follow-up to #6 and intended as a reminder to myself to explore other possibilities with initial rendering in server-side applications, which would generally involve generating some sort of CSS string.

**Comment by steida** [comment]
I think you can forget about it. I believe React will solve it itself soon and it's not a bottleneck. Please focus on your awesome work with the rebass. We need to make it usable with React Native ;-)

**Comment by steida** [comment]
There is no problem with #6, because the server will never have such information and it will be updated after initial render anyway.

**Comment by steida** [comment]
I was wrong. We need to detect a device on the server side to set sm, md, lg values. As far I know it's impossible to detect device screen size on the server, but I think we can expect default values for mobile, tablet, desktop device. Google Closure Library as a nice detection for that.

I believe we can use these constants https://github.com/twbs/bootstrap/blob/34291cc5cef1cf56d762eb6860dca92b3b9154c5/scss/_variables.scss#L126

**Comment by steida** [comment]
So what we need for the start is a way to bypass window.matchMedia on the server.
