### ISSUE TITLE
usage in React Native

### ISSUE THREAD

**Issue by walleXD** [jxnblk/reflexbox#16]
Would reflexbox work with react native?

**Comment by jxnblk** [comment]
I honestly haven't looked into React Native enough to know. I was under the assumption that React Native had its own implementation of CSS flexbox though.

**Comment by oliviertassinari** [comment]
Would be awesome if we could be using this lib on react native. They do have a flexbox implementation but not an API like this one. I really like the tradeoff of this API :+1:.

**Comment by steida** [comment]
Yeah, React Native has the almost the same Flexbox. 
https://facebook.github.io/react-native/docs/flexbox.html

There are some small changes:

> Note: On regular Flexbox, you’d be able to reverse the order of the items using ‘column-reverse’ and ‘row-reverse’, and specify the order of individual items by giving each item an order integer.

> Note: Missing on React Native is the reverse option (‘wrap-reverse’) as well as a way to specify the relationship between wrapped lines, called alignContent.

https://medium.com/@yoniweisbrod/a-mini-course-on-react-native-flexbox-2832a1ccc6#.ckwnv3uhz

It should work almost out of the box.
