### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by pocketjoso** [jxnblk/reflexbox#20]
React `15.x` cannot be used together with the current `v1.1.0` package (under `npm@2`) - this was already fixed in a6136c3813a4465e3cfaf4eadab9c09df250a161 - can you push the update to `npm` under a new (patch) version? :)

Thanks for package by the way!

**Comment by jxnblk** [comment]
Sorry, patch has been published.

**Comment by pocketjoso** [comment]
Cheers, thanks for super fast reply!
