### ISSUE TITLE
Failed propType: Invalid prop `is` supplied to `Flex`

### ISSUE THREAD

**Issue by bentatum** [jxnblk/reflexbox#22]
Hey again @jxnblk. Take a quick look at this. Maybe I'm doing it wrong.

```javascript
import { Link } from 'react-scroll'

<Flex is={Link}/>
```

produces ```Failed propType: Invalid prop `is` supplied to `Flex` ```... Though it still works for me.

A quick look at the propTypes suggests to me that by adding `React.PropTypes.func` to `Flex`'s `is` prop, might resolve this. I could submit a pull request if you'd like.

Or is it not a bug? Maybe I'm doing it wrong.

**Comment by nfcampos** [comment]
I have an open PR that fixes this (and some other small things) #21

**Comment by pahans** [comment]
I am experiencing this bug too. For both Flex and Box components prop validation doesn't accept a Component. It works if we pass a component to `is` prop but prop validation throws an error.

**Comment by jxnblk** [comment]
v2.0.0 is rewritten as a higher order component, and thus the `is` prop has been deprecated. To use the HOC, you can do something like the following:

```jsx
import { Link } from 'react-scroll'
import { Reflex } from 'reflexbox'

const CustomLink = (props) => (
  <Link {...props} />
)

export default Reflex(CustomLink)
```
