### ISSUE TITLE
Sizes sm/md/lg/ not updating when browser window width changes

### ISSUE THREAD

**Issue by kjetilge** [jxnblk/reflexbox#23]
On a box I have:
```<Box sm={12} lg={6} >```
I expect the box to be 100% wide when the window is narrow an 50% wide when window is wide/large.
Nothing happens when I resize the window. However, when I reload the page then the box show correct width. Is there something to configure to get this working responsively ?

**Comment by zanedev** [comment]
Seeing same thing

**Comment by hew** [comment]
https://github.com/jxnblk/reflexbox/issues/6

**Comment by jxnblk** [comment]
This is intentional by design to allow the end user to control window resize listeners within their own apps.

That said, I would like to support usage with another higher order component such as https://github.com/jxnblk/react-media-context

**Comment by SpencerCDixon** [comment]
Are there any examples of using react-media-context to get all the reflexbox's to automatically resize based on the window size??

**Comment by jxnblk** [comment]
I've started leaning more towards this approach. Need to clean up the branch and get this in at some point: https://github.com/jxnblk/reflexbox/blob/match-media-listeners/src/Reflex.js

**Comment by SpencerCDixon** [comment]
Nice that looks awesome, would love to get that merged in and start using :-) 

I've really enjoyed doing all my layout work with this library.  Thank you for making this!
