### ISSUE TITLE
"Stateless function components cannot be given refs"

### ISSUE THREAD

**Issue by contra** [jxnblk/reflexbox#30]
When adding a ref to any component exposed by this library. This is a pretty useful feature to have, my use case is pretty common: getting the height and width of the element so I can resize a canvas child.

Possible fix: Use https://github.com/troch/react-stateless which supports refs in stateless components, or use classes which you probably don't want to do

**Comment by jxnblk** [comment]
Does the v0.3 `baseRef` prop not work for what you're doing?

**Comment by jxnblk** [comment]
My bad. Wrong repo. Why didn't I just combine these two?

**Comment by contra** [comment]
@jxnblk Base component with the margin/padding/baseRef/etc sugar could definitely be split out of both of them

**Comment by contra** [comment]
It would be cool if everything in rebass was built on reflexbox too!

**Comment by jxnblk** [comment]
@contra FWIW, I think the HOC would allow you to add reflexbox props to anything in Rebass, but I haven't tried that out yet
