### ISSUE TITLE
Wrapper Component to reset Grid Size

### ISSUE THREAD

**Issue by bryaan** [jxnblk/reflexbox#34]
It would be nice to have a wrapper component to allow changing the default grid size from 12 to whatever is desired.  (and be able to nest within other grids of a different size)

```
<Grid size={10}>
...
</Grid>
```

**Comment by jxnblk** [comment]
I'm considering adding the ability to specify width as a fraction, e.g. `<Grid col={1 / 10} />` for values less than or equal to 1, and default to 12 column grid above 1 – e.g. `<Grid col={1 / 2} /> == <Grid col={6} />`.

I'm not sure if that's a confusing API, but it would allow for the flexibility that you're suggesting.

**Comment by mrsufgi** [comment]
for <Grid> only or for every <Reflex> component?

**Comment by jxnblk** [comment]
I think it would be across the board and handled here: https://github.com/jxnblk/understyle/blob/master/src/column.js#L5-L7

What I was suggesting is that numbers `2-12` would still behave as-is, but `1` would mean `100%` and `.5` would mean `50%`

**Comment by mrsufgi** [comment]
This behaviour is really straightforward and could provide more flexibility. 

@jxnblk can u assist me and @BryanARivera and give us a hint on how to instantiate reflexbox so it would call setColumns with a count parameter? (8, 10, 24 .. ). 

without rebuilding understyle package with a different number?

**Comment by jxnblk** [comment]
Not sure I follow... None of the width styles are handled in this repo, so it would need to be a change in the understyle module

**Comment by mrsufgi** [comment]
@jxnblk yeah, I had to change the source files of understyle to achieve 8 column grid, I guess your solution for fractures to define col sizes would be much better.
