### ISSUE TITLE
MS prefixing

### ISSUE THREAD

**Issue by sniepoort** [jxnblk/reflexbox#35]
I see you've added webkit prefixing. However, is there any reason why IE doesn't get prefixed? I see that your understyle library is set up to prefix with -ms-, but it's not functioning.

**Comment by AaronO** [comment]
@jxnblk `reflexbox` crashes on IE 11 (and presumably below), because's robox uses `understyle` @ `1.2.0` which calls `Number.isInteger` which doesn't exist on IE.

I think this is fixed in understyle's latest release because I couldn't find any calls to `Number.isInteger` in `master`.
