### ISSUE TITLE
Flexbox property clarification

### ISSUE THREAD

**Issue by TheoMer** [jxnblk/reflexbox#37]
Can I, or would I say how do I, specify the following?:

`<Flex min-height="100vh">`
`<Box flex="0 0 auto">Header</Box>`
`<Box flex="1 0 auto">Content</Box>`
`<Box flex="0 0 auto">Title</Box>`
`<Flex>`

**Comment by bentatum** [comment]
```js
<Flex style={{ minHeight: '100vh' }}>
  <Box auto>Header</Box>
  <Box auto>Content</Box>
  <Box auto>Title</Box>
<Flex>
```

**Comment by jxnblk** [comment]
@TheoMer Currently there isn't support for different `flex` properties. Setting `auto` just sets `flex='1 1 auto'` (see https://github.com/jxnblk/understyle/blob/master/src/flex.js#L23), but I think there's a use-case for setting the `flex` property with a string like you're doing.

**Comment by TheoMer** [comment]
@jxnblk That would be very helpful, as [flexbox-react](https://github.com/nachoaIvarez/flexbox-react) already allows for this:

`<Flexbox flex="1 0 auto" />`

**Comment by smashercosmo** [comment]
[Angular Material Layout](https://material.angularjs.org/latest/layout/children) for inspiration. Check the "Additional Flex Values" section.

**Comment by TheoMer** [comment]
@smashercosmo Cool!

**Comment by jay-khatri** [comment]
@jxnblk Any chance you'd accept a PR to add the height as a new prop?

**Comment by jxnblk** [comment]
@jay-khatri You might want to check out [grid-styled](https://github.com/jxnblk/grid-styled/), which has a `css` prop which would let you set height if needed

**Comment by ryan2clw** [comment]
Just use styled-components to add the height, example follows:
```
import React from 'react';
import styled from 'styled-components';
import PropTypes from 'prop-types';
import { Flex } from 'reflexbox';

import './styles/Square.css';

/**
 * This component is a small number square which makes up a row on a player
 * ticket. The component manages style based on whether or not the 'called' prop
 * is passed down to it.
 * @class
 */
const FlexHeight = styled(Flex)`
  height: ${props => props.height || "54px"};
`;

class Square extends React.Component {

  constructor(props){
    super(props);
    console.log("SQUARE", this.props);
  }

  width = () => this.props.width || "54px";
  height = () => this.props.height || "54px";
  render() {
    return(
      <FlexHeight height={this.height()} w={this.width()} p={1} justify='center' align='center' className={'ticket-number ' + (this.props.called ? 'called' : '')}>
          {this.props.ticketNumber}
      </FlexHeight>
    )
  }
}

Square.propTypes = {
  ticketNumber: PropTypes.string,
  called: PropTypes.bool,
};
export default Square;
```
