### ISSUE TITLE
publish latest version on npm plz :)

### ISSUE THREAD

**Issue by kunchenguid** [jxnblk/reflexbox#4]
@jxnblk 
this is an awesome project! among all the react flexbox implementations I think this one has the most elegant interface. 
npm still has rc1 as latest release. would be good to have all the latest changes.

**Comment by jxnblk** [comment]
Yeah, will do. In the meantime you can specify the newer versions on install. They should be published, just not `@latest`

**Comment by jxnblk** [comment]
Bumped the rc version and left the tag at `latest`, so I think it should grab the actual latest now.

**Comment by kunchenguid** [comment]
thanks! rc9 is the latest now.
