### ISSUE TITLE
Higher order components should begin with the lower case

### ISSUE THREAD

**Issue by steida** [jxnblk/reflexbox#40]
Reflex => reflex

Otherwise, people can be confused to use it as regular component `<Reflex`.

**Comment by jxnblk** [comment]
Yeah, I've thought about this. I like the naming convention from recompose and was thinking `withReflex`, but will need to keep things backwards compatible by also exporting it as `Reflex`

**Comment by steida** [comment]
Just bump 3. It's no shame, to be honest.

**Comment by jxnblk** [comment]
It's not about shame, it's an easy thing to handle without requiring users to manually upgrade

**Comment by jxnblk** [comment]
Renamed the HOC to `withReflex` in the latest release
