### ISSUE TITLE
Merge style prop

### ISSUE THREAD

**Issue by aaronjensen** [jxnblk/reflexbox#45]
It looks like 2.2.0 broke passing `style` down to reflex'd components due to the grid addition: https://github.com/jxnblk/reflexbox/blob/88b9d7cb114be88c1d5bd61a712f334c51b14787/src/withReflex.js#L102

I can work around it w/ classes for now, but it'd be nice to have this back. Thanks!

**Comment by varmil** [comment]
I have the same problem 👍

**Comment by contra** [comment]
Yeah, also getting this issue - seems to be a pretty major regression on a non-breaking change, not sure if this was supposed to be intended or just an oversight.

**Comment by SpencerCDixon** [comment]
yeah this just borked my whole app haha.  Probably an oversight

**Comment by jxnblk** [comment]
Yup, sorry about that. Just published a patch. Let me know if you still see issues 😬

**Comment by SpencerCDixon** [comment]
Looking good!  Thanks for the quick fix :-)
