### ISSUE TITLE
Request: ability to set order based on breakpoints

### ISSUE THREAD

**Issue by angusfretwell** [jxnblk/reflexbox#49]
It would be great if it was possible to set `order` based on the breakpoint. Something like `smOrder`, `mdOrder`, etc. Not too sure how to implement this, if you could point me in the right direction I would be happy to send a PR 😄

**Comment by wstam88** [comment]
You could listen for resize event and adjust the order of the items with jQuery
```
var _window = jQuery(window);
var $iW = _window.innerWidth();

if ($iW < 767) {
    jQuery('#grid_right').insertBefore('#grid_left');
} else {
    jQuery('#grid_right').insertAfter('#grid_left');
}
```

**Comment by kolpav** [comment]
It would be very nice to be able to control `flex-direction` based on breakpoints as well.
@jxnblk What do you think about this is? Is it something worth adding into this library?
