### ISSUE TITLE
Could you add some documentation on how to use setBreakpoint?

### ISSUE THREAD

**Issue by sorahn** [jxnblk/reflexbox#5]
Am I correct to assume it's possible to set up my own breakpoints object and pass it in some how?  I see it in the src folder.

And would using such a function set it globally, or for a specific <Flex>.

<Flex breakpoints={myCustomBreakpoints}> might be cool too.  Not sure how hard that would be...

**Comment by jxnblk** [comment]
I'm working on cleaning things up for v1 and will document both `setBreakpoints` and `setScale`, which both work globally, not per component. In the meantime you can look at the tests to get a sense of how they work.

That said the `sm`, `md`, and `lg` props are probably going to change to make things more customizable.

**Comment by sorahn** [comment]
Awesome.

Yesterday I started digging around the docs app and I think I've got a handle on it.  I was going to ask about the `sm|md|lg` being static, but It looks like you're ahead of me :)

:+1:

**Comment by jxnblk** [comment]
Just a heads up, I'm changing the implementation of `scale` and `breakpoints` to use React context instead of the custom solution I had previously. README should reflect the new configuration usage, and I'll be publishing an updated version soon.

**Comment by sorahn** [comment]
Thanks for the heads up.  Are you going to release that as another major version number, or should I shrinkwrap our component until I have time to implement the changes.

**Comment by sorahn** [comment]
Nevermind, I see you already released it as 1.1.0.  I'll just stick a ~ infront of our version for now.  Thanks!

**Comment by jxnblk** [comment]
Oh, I guess I didn't really think about how that might've introduced breaking changes... :disappointed: 

Hope that didn't cause any major issues on your end.

**Comment by sorahn** [comment]
Nope! We're all good. I locked the version in package.json so a new npm install won't pick up the patch. I should be able to pull down the new version later this week.
