### ISSUE TITLE
reduce # of wrapper components

### ISSUE THREAD

**Issue by contra** [jxnblk/reflexbox#52]
Is there any way to do this currently? This makes debugging hard, performance for updating a little worse, and perf debugging using react-addons-perf impossible (due to obscured names).

Every Flex component adds two levels of nesting (minimum):
![image](https://cloud.githubusercontent.com/assets/425716/22668464/cde90df0-ec8e-11e6-8def-1903e6497a57.png)

Here's what a perf report looks like using react-addons-perf:
![image](https://cloud.githubusercontent.com/assets/425716/22668528/02fb4e22-ec8f-11e6-8451-c279276c0907.png)

Temporary work-around is to revert to 1.x which had simpler components w/ no wrappers

**Comment by jxnblk** [comment]
This should be less of an issue with v3, but let me know if you're still having issues
