### ISSUE TITLE
Warning: Accessing PropTypes deprecated

### ISSUE THREAD

**Issue by timscott** [jxnblk/reflexbox#57]
I'm getting this using React 15.5.4.

```
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
```

The issue appears to be in robox [here](https://github.com/jxnblk/robox/blob/master/src/Robox.js#L67). I'm submitting the issue here, since my app does not depend on robox directly, and it seems to be the same owner.

**Comment by hozefaj** [comment]
#55 addresses this.

**Comment by jxnblk** [comment]
Thanks! Should be fixed in v3
