### ISSUE TITLE
Does the responsive layout work without javascript?

### ISSUE THREAD

**Issue by KyleAMathews** [jxnblk/reflexbox#6]
For server-rendered stuff, this is important. Wasn't sure from quick look around.

**Comment by jxnblk** [comment]
It uses matchMedia, so no. Flex wrap can get you part of the way, but this is definitely just an experiment with one approach. Lately, I've been leaning towards plain css solutions for responsive page layout, but would love to hear if you have any thoughts on how to handle this.
