### ISSUE TITLE
Problem with removed border-box and missing docs

### ISSUE THREAD

**Issue by frwickst** [jxnblk/reflexbox#71]
I've been using version 2.2.3 for a while now and was about to upgrade to the newest version when I noticed two things.

1. I can't find any information of what has changed in v.3. It seems like a complete overhaul of the code and many things has changed.

2. And this is the thing that completely breaks compatibility for me and. Before, this package seemed to have been using Robox. That package set the attribute `boxSizing: 'border-box'` on Boxes but this is no longer true right now. This means that when I do things such as three elements with w=0.33 and px=2 this will not fit in one row and I get two rows instead. The border-box took care of this but has since been removed. Is there any good remedy for this? Is this is bug? Is this change done of purpose?

**Comment by me717** [comment]
@jxnblk Is there any chance on this issue being resolved?
