### ISSUE TITLE
Make a HOC version

### ISSUE THREAD

**Issue by jgoux** [jxnblk/reflexbox#9]
Hello,

I really like the API you built for this library. :+1: 

What would be the scenario when you want to integrate with custom/third-party components ?

For example, imagine I want to create a layout using multiple [Paper](http://www.material-ui.com/#/components/paper) from material-ui.

To make the `Paper` a flex element, I'd have to modify its `style` property (this is what I do at the moment), but I could do better and encapsulate all the "position/layout" logic inside HOC components which would apply the flexbox styles to their children, taking the API you provide : 
```jsx
import { AppBar, Paper } from "material-ui"
import { Box, Flex, Boxed, Flexed } from "reflexbox"

const view = (props) =>

<Flex auto column>
  <AppBar />
  <Flex auto>
    {/* Apply the styles generated from <Boxed auto> to <Paper>Left</Paper> */}
    <Boxed auto>
      <Paper>Left</Paper>
    </Boxed>
    <Boxed auto>
      <Paper>Right</Paper>
    </Boxed>
  </Flex>
</Flex>
```

I used `Boxed` and `Flexed` but the name/API could be anything.

What do you think ? :smile:

**Comment by jxnblk** [comment]
I've certainly been thinking about this. I was thinking more of having an API that looks something like this, but maybe there's good reason not to go with this approach:

```jsx
<Box
  Component={Paper}
  {...boxProps}
  {...paperProps} />
```

The Box component would pass styles based on its props, then render Paper. Curious what you think

**Comment by jgoux** [comment]
I think it's a matter of taste.

I prefer seeing a component's own props attached to its tag.
I also prefer seeing the tags tree composition, it reduces the cognitive load **for me**.

So I don't have a definitive answer for this, but I'm also curious of reading others opinions. :interrobang:

**Comment by mrtnbroder** [comment]
I'm with @jgoux. I'd prefer seeing my props on the component tag.

**Comment by jxnblk** [comment]
I'm not opposed to the nested component approach. One thing that feels odd to me is that the jsx looks like two elements, but it's only generating one. Maybe that's an okay trade off in this situation.

**Comment by jgoux** [comment]
We could also use a simple function:
```jsx
import { AppBar, Paper } from "material-ui"
import { Box, Flex, box, flex } from "reflexbox"

const view = (props) =>

<Flex auto column>
  <AppBar />
  <Flex auto>
  {box({ auto: true })(
    <Paper>Left</Paper>
  )}
  {box({ auto: true })(
    <Paper>Right</Paper>
  )}
  </Flex>
</Flex>
```

With the partial application, you can even prepare common patterns : 
```jsx
import { AppBar, Paper } from "material-ui"
import { Box, Flex, box, flex } from "reflexbox"

const CustomBox = box({ auto: true })

const view = (props) =>

<Flex auto column>
  <AppBar />
  <Flex auto>
  {CustomBox(
      <Paper>Left</Paper>
  )}
  {CustomBox(
    <Paper>Right</Paper>
  )}
  </Flex>
</Flex>
```

**Comment by jxnblk** [comment]
The latest version `1.1.0` supports an `is` prop to pass components or elements to render as the root. I'll take a stab at wrapper component as well at some point.

**Comment by jgoux** [comment]
Congrats for the release ! :+1:
